@startuml classDiagram

title Circuit Simulation class diagram
right footer "20-05-11 v2.0"

hide empty members

class logicGate as "LogicGate" {
}

abstract class node as "Node" {
    - inputs : vector<bool>
    - outputs : vector<bool>
    - name : string
    - nextNodeName : string

    + propagationDelay : int
    + run() : int 
    + setValue(value : bool)
}

class logicFunction as "LogicFunction" {

}

class circuit as "Circuit" {
    'store nodes by name as identifier'
    - nodes : map<int, node*>
    - nodeNameToId : map<string, int>;
    - sortedIds : vector<int>

    + run() : result
    + addNode(node : node*)
    + sortNodes()
    + getNodeIdByName(name : string) : int
    + {static} createCircuit(fileName : string) : Circuit*
}

class input as "Input" {
}
class probe as "Probe" {
    + printResult(result : int)
}

class nodeFactory as "NodeFactory" {
    + {static} instance : NodeFactory*
    + {static} createNode(nodeType : string, name : string) : node*
}

class fileReader as "FileReader" {
    + {static} readFile(fileName : string) : Circuit*
}

node *-- circuit

input --|> node
probe --|> node
logicGate --|> node

logicGate *-- logicFunction

andFunction --|> logicFunction
orFunction --|> logicFunction
notFunction --|> logicFunction
nandFunction --|> logicFunction
norFunction --|> logicFunction
xorFunction --|> logicFunction

@enduml